#!/bin/sh

ln -s -f ~/dot_files/.zshrc ~/.zshrc
ln -s -f ~/dot_files/.zshrc.mine ~/.zshrc.mine
ln -s -f ~/dot_files/.vimrc ~/.vimrc
ln -s -f ~/dot_files/.vimrc.plugin ~/.vimrc.plugin
/bin/ln -s -f -h ~/dot_files/.vim ~/.vim
ln -s -f ~/dot_files/.tmux.conf ~/.tmux.conf
ln -s -f ~/dot_files/.tmux.local.conf ~/.tmux.local.conf
ln -s -f ~/dot_files/powerline ~/.config/powerline
ln -s -f ~/dot_files/.gitignore_global ~/.gitignore
ln -s -f ~/dot_files/.gemrc ~/.gemrc
ln -s -f ~/dot_files/.pryrc ~/.pryrc
ln -s -f ~/dot_files/dircolors.256dark ~/dircolors.256dark
git config --global core.excludesfile ~/.gitignore
